---
title: "R Notebook"
output: html_notebook
---

```{r}
adult<-read.csv('adult.csv')
str(adult)
```

missing values
duplicates
```{r}
sum(is.na(adult))
sum(duplicated(adult))

```

```{r}
require(dplyr)
adult<- distinct(adult)
```


```{r}
table(adult$income)

```

```{r}

```




```{r}
require(ggplot2)
adult$income[which(adult$income=='>50K')]<-1
adult$income[which(adult$income=='<=50K')]<-0
```


```{r}
table(adult$native.country)
names(adult)
```



```{r}
adult$workclass[which(adult$workclass=='?')]<- 'unknown'
```



```{r}
adult$occupation[which(adult$occupation=='?')]<-'unknow'
```


```{r}
adult$native.country[which(adult$native.country=='?')]<-'unknow'

```


```{r}

plot(quantile(adult$age,seq(0,1,0.1)))
quantile(adult$age,seq(0,1,0.1))
adult$age[adult$age>58]<-58
```



```{r}
plot(quantile(adult$fnlwgt,seq(0,1,0.1)))
quantile(adult$fnlwgt,seq(0,1,0.1))
adult$fnlwgt[adult$fnlwgt>328466.0]<-328466.0
```



```{r}
plot(quantile(adult$educational.num,seq(0,1,0.1)))
quantile(adult$educational.num,seq(0,1,0.1))


```




```{r}
plot(quantile(adult$hours.per.week,seq(0,1,0.1)))
quantile(adult$hours.per.week,seq(0,1,0.1))
adult$hours.per.week[adult$hours.per.week>55]<-55
```



```{r}
ggplot(adult,aes(x=age))+geom_bar(fill='skyblue')


```

```{r}
ggplot(adult, aes(x = workclass)) + 
  geom_bar(fill = 'skyblue',color = 'black') + coord_flip()
reg_df <- group_by(adult, workclass) %>% 
          summarise(reg_strength = n()) %>%
          arrange(reg_strength)

```



```{r}


```



```{r}
ggplot(adult,aes(x=income,fill=gender))+geom_bar()

```


```{r}
ggplot(adult, aes(x = occupation)) + 
  geom_bar(fill = 'skyblue',color = 'black') + coord_flip()


```


```{r}
ggplot(adult,aes(x=education,fill=income))+geom_bar()+coord_flip()
```

```{r}
adult$education<- NULL
```


```{r}
ggplot(adult,aes(x=marital.status,fill=income))+geom_bar()+coord_flip()

```


```{r}
adult$marital.status<-NULL

```


```{r}
ggplot(adult, aes(x = native.country)) + 
  geom_bar(fill = 'skyblue',color = 'black') + coord_flip()

```



```{r}
adult$native.country<-NULL

```

```{r}

ggplot(adult,aes(x=income,y=hours.per.week))+geom_boxplot(fill='darkgreen')
```

feature engineering
```{r}
str(adult)

```



```{r}
adult[,c(1,3,4,9,10,11)]<-sapply(adult[,c(1,3,4,9,10,11)],scale)
```

```{r}
 round(prop.table(table(new_data$income)) * 100, 2)
```


changing imbalnce to balance
```{r}
require(ROSE)
new_data<-ovun.sample(income~.,data = adult,method ='both' ,N = 48790)$data
```


```{r}
table(new_data$income)
```

```{r}
require(dummies)
dummy<-dummy.data.frame(as.data.frame(new_data[,-12]))

```


```{r}
df<-bind_cols(dummy,new_data['income'])
```

```{r}
table(df$income)
df$income<-as.factor(df$income)
```

```{r}
set.seed(100)
require(caTools)
i<-sample.split(df$income,SplitRatio = 0.75)
train<-df[i,]
test<-df[!i,]
```



```{r}
train_labels<-train$income
test_labels<-test$income



```



```{r}
require(class)
model<-knn(train =train[,-44],cl = train_labels,test = test[,-44],k = 15)
summary(model)
```

```{r}
require(caret)

confusionMatrix(model, test_labels)
```

