---
title: "R Notebook"
output: html_notebook
---
 

```{r}
mobile<-read.csv('train.csv')
str(mobile)
```

checking null and duplicated values

```{r}
sum(is.na(mobile))
sum(duplicated(mobile))

```
perfectly balabced data
```{r}
table(mobile$price_range)
```

cheking outliers
```{r}
plot(quantile(mobile$battery_power,seq(0,1,0.1)))
quantile(mobile$battery_power,seq(0,1,0.1))
```


```{r}
plot(quantile(mobile$clock_speed,seq(0,1,0.1)))
quantile(mobile$clock_speed,seq(0,1,0.1))
```


```{r}
plot(quantile(mobile$int_memory,seq(0,1,0.1)))
quantile(mobile$int_memory,seq(0,1,0.1))
```


```{r}
plot(quantile(mobile$m_dep,seq(0,1,0.1)))
quantile(mobile$m_dep,seq(0,1,0.1))
```

```{r}

plot(quantile(mobile$mobile_wt,seq(0,1,0.1)))
quantile(mobile$mobile_wt,seq(0,1,0.1))
```


```{r}
require(dplyr)
plot(quantile(mobile$px_height,seq(0,1,0.1)))
quantile(mobile$px_height,seq(0,1,0.1))
mobile$px_height[which(mobile$px_height>1285.0)]<-1285.0
```


```{r}
plot(quantile(mobile$px_width,seq(0,1,0.1)))
quantile(mobile$px_width,seq(0,1,0.1))

```


```{r}
plot(quantile(mobile$ram,seq(0,1,0.1)))
quantile(mobile$ram,seq(0,1,0.1))

```



```{r}
plot(quantile(mobile$sc_h,seq(0,1,0.1)))
quantile(mobile$sc_h,seq(0,1,0.1))
```



```{r}
plot(quantile(mobile$sc_w,seq(0,1,0.1)))
quantile(mobile$sc_w,seq(0,1,0.1))
mobile$sc_w[which(mobile$sc_w>12)]<-12
```



```{r}
plot(quantile(mobile$talk_time,seq(0,1,0.1)))
quantile(mobile$talk_time,seq(0,1,0.1))
```

Perform Univariate and Bivariate analysis
```{r}
require(ggplot2)
ggplot(mobile,aes(x=price_range,fill=as.factor(blue)))+geom_bar()
```


```{r}
ggplot(mobile,aes(x=as.factor(four_g),fill=as.factor(price_range)))+geom_bar()
```

```{r}
ggplot(mobile,aes(x=price_range,fill=as.factor(dual_sim)))+geom_bar()
```

```{r}
ggplot(mobile,aes(x=battery_power,y=mobile_wt))+geom_point()
```


```{r}
ggplot(mobile,aes(x=as.factor(price_range),y=battery_power))+geom_boxplot(fill='darkgreen')
```

feature engineering
```{r}
mobile[,c(1,3,5,7:9,11:17)]<-sapply(mobile[,c(1,3,5,7:9,11:17)],scale)
```

create dummies for categorical variables
```{r}
str(mobile)
```


```{r}
set.seed(102)
require(caTools)
i<-sample.split(mobile$price_range,SplitRatio = 0.75)
train<-mobile[i,]
test<-mobile[!i,]
```

```{r}
train<- mutate_if(train, is.integer, as.factor)
test<-  mutate_if(test, is.integer, as.factor)             
```





```{r}
require(randomForest)
set.seed(10)
rf_model <- randomForest(price_range ~ ., train, ntree = 1000,
                         do.trace = 50, importance = T)
```

```{r}
require(varImp)
require(rpart)
varImp(rf_model)

varImpPlot(rf_model)
```


```{r}
rf_pred <- predict(rf_model,test)

summary(rf_pred)
```


```{r}
test$price_range_pred<-rf_pred
```


```{r}

```

```{r}
confusionMatrix(test$price_range,test$price_range_pred)
```


```{r}

...